server:
  port: 7080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  level:
    root: warn
    com: info
  file:
    name: logs/uni-gateway.log

zookeeper:
  url: 127.0.0.1:22181
  namespace: admin
  node: /uni-register