server:
  port: 7080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    database: 1
    host: 192.168.0.110
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 5000

logging:
  level:
    root: warn
    com: info
  file:
    name: logs/uni-gateway.log